# Project Stage 1 Report

Group #3  
Project topic: Movie Revenue Forecasting  
Dataset url: https://www.kaggle.com/datasets/tmdb/tmdb-movie-metadata

## Task 1: Problem Framing

Your understanding of the project (what you want to study or predict).
Write 4-6 sentences describing: the task (classification/regression/..);
who/what benefits from this study; why this dataset fits (size, feature)

The task for this project is a regression problem, where the goal is to predict a movie’s revenue using features such as budget, genre, popularity, voter average, and the total votes . These features provide useful information since budget is directly related to production scale, while popularity and voting metrics capture audience engagement. This study would benefit film studios, investors, and streaming platforms, who can use the predictions to estimate financial performance before release. It can be looked at as a classification task, where the same features could be used to label movies as “successful” or “unsuccessful” based on revenue thresholds. The dataset is appropriate because it has a large number of movies and contains both numerical and categorical features, allowing for a thorough analysis and meaningful predictions.

## Task 2: Dataset Exploration
### Importing the Dataset
Here we download the dataset directly from kaggle.

In [11]:
# Only need to run once to download dataset locally.
!pip install kagglehub pandas
import kagglehub
path = kagglehub.dataset_download("tmdb/tmdb-movie-metadata")

Requirement already satisfied: kagglehub in c:\users\matth\anaconda3\lib\site-packages (0.3.13)
Requirement already satisfied: pandas in c:\users\matth\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: packaging in c:\users\matth\anaconda3\lib\site-packages (from kagglehub) (24.2)
Requirement already satisfied: pyyaml in c:\users\matth\anaconda3\lib\site-packages (from kagglehub) (6.0.2)
Requirement already satisfied: requests in c:\users\matth\anaconda3\lib\site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in c:\users\matth\anaconda3\lib\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: numpy>=1.26.0 in c:\users\matth\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\matth\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\matth\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\matth\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\matth\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\matth\anaconda3\lib\site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\matth\anaconda3\lib\site-packages (from requests->kagglehub) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\matth\anaconda3\lib\site-packages (from requests->kagglehub) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\matth\anaconda3\lib\site-packages (from requests->kagglehub) (2025.4.26)
Requirement already satisfied: colorama in c:\users\matth\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)

Next we load the 2 datasets into dataframs 'movies' and 'credits'.

In [12]:
# Need to run every time to import dataset into notebook.
import os
import pandas as pd

# import movies

csv_file = os.path.join(path, "tmdb_5000_movies.csv")
movies = pd.read_csv(csv_file)

# import credits

csv_file = os.path.join(path, "tmdb_5000_credits.csv")
credits = pd.read_csv(csv_file)

We perform an outer merge on the movie id, combining the dataframes.

In [14]:
# merge
df = pd.merge(movies, credits, left_on='id', right_on='movie_id', how='outer')

Here we display the first 10 rows of our dataset.

In [16]:
# First 10 rows (Stage 1, Task 2)
df.head(10)

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,movie_id,title_y,cast,crew
0,4000000,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 35, ""name...",NaN,5,"[{""id"": 612, ""name"": ""hotel""}, {""id"": 613, ""na...",en,Four Rooms,It's Ted the Bellhop's first night on the job....,22.876230,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Twelve outrageous guests. Four scandalous requ...,Four Rooms,6.5,530,5,Four Rooms,"[{""cast_id"": 42, ""character"": ""Ted the Bellhop...","[{""credit_id"": ""52fe420dc3a36847f800012d"", ""de..."
1,11000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 28, ""...",http://www.starwars.com/films/star-wars-episod...,11,"[{""id"": 803, ""name"": ""android""}, {""id"": 4270, ...",en,Star Wars,Princess Leia is captured and held hostage by ...,126.393695,"[{""name"": ""Lucasfilm"", ""id"": 1}, {""name"": ""Twe...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"A long time ago in a galaxy far, far away...",Star Wars,8.1,6624,11,Star Wars,"[{""cast_id"": 3, ""character"": ""Luke Skywalker"",...","[{""credit_id"": ""52fe420dc3a36847f8000437"", ""de..."
2,94000000,"[{""id"": 16, ""name"": ""Animation""}, {""id"": 10751...",http://movies.disney.com/finding-nemo,12,"[{""id"": 494, ""name"": ""father son relationship""...",en,Finding Nemo,"Nemo, an adventurous young clownfish, is unexp...",85.688789,"[{""name"": ""Pixar Animation Studios"", ""id"": 3}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"There are 3.7 trillion fish in the ocean, they...",Finding Nemo,7.6,6122,12,Finding Nemo,"[{""cast_id"": 8, ""character"": ""Marlin (voice)"",...","[{""credit_id"": ""52fe420ec3a36847f80006b1"", ""de..."
3,55000000,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...",NaN,13,"[{""id"": 422, ""name"": ""vietnam veteran""}, {""id""...",en,Forrest Gump,A man with a low IQ has accomplished great thi...,138.133331,"[{""name"": ""Paramount Pictures"", ""id"": 4}]",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"The world will never be the same, once you've ...",Forrest Gump,8.2,7927,13,Forrest Gump,"[{""cast_id"": 7, ""character"": ""Forrest Gump"", ""...","[{""credit_id"": ""52fe420ec3a36847f800076b"", ""de..."
4,15000000,"[{""id"": 18, ""name"": ""Drama""}]",http://www.dreamworks.com/ab/,14,"[{""id"": 255, ""name"": ""male nudity""}, {""id"": 29...",en,American Beauty,"Lester Burnham, a depressed suburban father in...",80.878605,"[{""name"": ""DreamWorks SKG"", ""id"": 27}, {""name""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Look closer.,American Beauty,7.9,3313,14,American Beauty,"[{""cast_id"": 6, ""character"": ""Lester Burnham"",...","[{""credit_id"": ""52fe420ec3a36847f8000809"", ""de..."
5,12800000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 80, ""name...",NaN,16,"[{""id"": 30, ""name"": ""individual""}, {""id"": 246,...",en,Dancer in the Dark,"Selma, a Czech immigrant on the verge of blind...",22.022228,"[{""name"": ""Fine Line Features"", ""id"": 8}, {""na...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,You don't need eyes to see.,Dancer in the Dark,7.6,377,16,Dancer in the Dark,"[{""cast_id"": 33, ""character"": ""Selma Jezkova"",...","[{""credit_id"": ""52fe420ec3a36847f8000981"", ""de..."
6,90000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",NaN,18,"[{""id"": 402, ""name"": ""clone""}, {""id"": 444, ""na...",en,The Fifth Element,"In 2257, a taxi driver is unintentionally give...",109.528572,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,There is no future without it.,The Fifth Element,7.3,3885,18,The Fifth Element,"[{""cast_id"": 5, ""character"": ""Korben Dallas"", ...","[{""credit_id"": ""52fe420fc3a36847f8000c09"", ""de..."
7,92620000,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 878, ""nam...",NaN,19,"[{""id"": 312, ""name"": ""man vs machine""}, {""id"":...",de,Metropolis,In a futuristic city sharply divided between t...,32.351527,"[{""name"": ""Paramount Pictures"", ""id"": 4}, {""na...",...,"[{""iso_639_1"": ""xx"", ""name"": ""No Language""}]",Released,There can be no understanding between the hand...,Metropolis,8.0,657,19,Metropolis,"[{""cast_id"": 10, ""character"": ""Maria"", ""credit...","[{""credit_id"": ""52fe420fc3a36847f8000c55"", ""de..."
8,0,"[{""id"": 18, ""name"": ""Drama""}, {""id"": 10749, ""n...",http://www.clubcultura.com/clubcine/clubcineas...,20,"[{""id"": 455, ""name"": ""farewell""}, {""id"": 457, ...",en,My Life Without Me,A Pedro Almodovar production in which a fatall...,7.958831,"[{""name"": ""El Deseo"", ""id"": 49}, {""name"": ""Mil...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,NaN,My Life Without Me,7.2,77,20,My Life Without Me,"[{""cast_id"": 5, ""character"": ""Ann"", ""credit_id...","[{""credit_id"": ""52fe420fc3a36847f8000d1d"", ""de..."
9,140000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneyvideos/liveaction/p...,22,"[{""id"": 911, ""name"": ""exotic island""}, {""id"": ...",en,Pirates of the Caribbean: The Curse of the Bla...,"Jack Sparrow, a freewheeling 17th-century pira...",271.972889,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,Prepare to be blown out of the water.,Pirates of the Caribbean: The Curse of the Bla...,7.5,6985,22,Pirates of the Caribbean: The Curse of the Bla...,"[{""cast_id"": 12, ""character"": ""Captain Jack Sp...","[{""credit_id"": ""52fe420fc3a36847f8000f11"", ""de..."

### Dataset Dictionary
This code creates a dataset dictionary listing our 25 features, their data type, an example entry, and % entries missing. We also assigned revenue as our target feature.

In [17]:
# Task 2: Create a dataset dictionary
dataset_dict = pd.DataFrame({
    "Feature": df.columns,
    "Type": [df[col].dtype for col in df.columns],
    "Example": [df[col].dropna().iloc[0] for col in df.columns],  
    "Missing %": [df[col].isna().mean() * 100 for col in df.columns]
})

# Add target variable at the end
dataset_dict.loc[len(dataset_dict)] = [
    "Target Variable (revenue)",  
    df["revenue"].dtype,         
    df["revenue"].dropna().iloc[0], 
    df["revenue"].isna().mean() * 100 
]

dataset_dict

,Feature,Type,Example,Missing %
0,budget,int64,4000000,0.000000
1,genres,object,"[{""id"": 80, ""name"": ""Crime""}, {""id"": 35, ""name...",0.000000
2,homepage,object,http://www.starwars.com/films/star-wars-episod...,64.355611
3,id,int64,5,0.000000
4,keywords,object,"[{""id"": 612, ""name"": ""hotel""}, {""id"": 613, ""na...",0.000000
5,original_language,object,en,0.000000
6,original_title,object,Four Rooms,0.000000
7,overview,object,It's Ted the Bellhop's first night on the job....,0.062461
8,popularity,float64,22.87623,0.000000
9,production_companies,object,"[{""name"": ""Miramax Films"", ""id"": 14}, {""name"":...",0.000000
10,production_countries,object,"[{""iso_3166_1"": ""US"", ""name"": ""United States o...",0.000000
11,release_date,object,1995-12-09,0.020820
12,revenue,int64,4300000,0.000000
13,runtime,float64,98.0,0.041641
14,spoken_languages,object,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",0.000000
15,status,object,Released,0.000000
16,tagline,object,Twelve outrageous guests. Four scandalous requ...,17.572351
17,title_x,object,Four Rooms,0.000000
18,vote_average,float64,6.5,0.000000
19,vote_count,int64,530,0.000000
20,movie_id,int64,5,0.000000
21,title_y,object,Four Rooms,0.000000
22,cast,object,"[{""cast_id"": 42, ""character"": ""Ted the Bellhop...",0.000000
23,crew,object,"[{""credit_id"": ""52fe420dc3a36847f800012d"", ""de...",0.000000
24,Target Variable (revenue),int64,4300000,0.000000

## Task 3 — Feature Exploration 
### Abdel
I cleaned a few features:

- runtime: filled missing values with the median
- budget and revenue: replaced 0 with NaN
- homepage and tagline: dropped because they had too many missing

Now the data looks cleaner for later analysis.

In [18]:
import numpy as np

df["runtime"] = df["runtime"].fillna(df["runtime"].median())

df["budget"] = df["budget"].replace(0, np.nan)
df["revenue"] = df["revenue"].replace(0, np.nan)

df = df.drop(["homepage","tagline"], axis=1)

print("cleaned runtime, budget, revenue, homepage, tagline")

cleaned runtime, budget, revenue, homepage, tagline

### Matthew

Before merging, both data sets had identical 'id' and 'title' columns, which created duplicates in the merge. So, I removed the duplicates, making a single 'id' and 'title' column.

In [19]:
df = df.drop(["movie_id"], axis=1)
df = df.drop(["title_y"], axis=1)
df = df.rename(columns={"title_x": "title"})

### Trey

I went and looked over all data to ensure the set was clean. 
After analysis, it seems we have cleaned the data set well and taken into account entries that werent proper and replaced them with NAN (not a number) to ensure the system doesnt read them and skew the data. Doing this ensures that the means or averages are not skewed for things like Budget and Revenue.

Lots of the columns were hard to read, and looked to be stored as a dictionary, so I converted them into comma separated lists.
Example: '[{"id": 80, "name": "Crime"}, {"id": 35, "name": "Comedy"}]' becomes 'Crime, Comedy'

In [20]:
import ast

# List of columns that need conversion
json_cols = ['genres', 'keywords', 'cast', 'production_companies', 'production_countries', 'spoken_languages', 'crew']

for col in json_cols:
    df[col] = df[col].apply(lambda s: ", ".join(d['name'] for d in ast.literal_eval(s)) if s else "")

### Liyah

Reordered columns to group similar columns, and follow the general order of id, target, numeric data, lists, metadata.

In [22]:
df = df[['id', 'revenue', 'budget', 'runtime', 'popularity', 'vote_average', 'vote_count', 'genres', 'keywords', 'cast', 'crew', 'production_companies', 'production_countries', 'spoken_languages', 'title', 'original_title', 'overview', 'release_date', 'status', 'original_language']]

### Shauna

I performed a chi-squared test on numeric variables to see if they are normally distributed. Since the p-values are very small, it would not be appropriate to remove outliers with a z-score >3 or <-3.

In [23]:
import scipy.stats as stats

numeric_cols = ['budget', 'runtime', 'popularity', 'vote_average', 'vote_count', 'revenue']

print("Chi-Squared test:")
for col in numeric_cols:
    col_data = df[col].dropna()  
    stat, p = stats.normaltest(col_data)
    print(f"{col}: p={p:.3e}")

Chi-Squared test:
budget: p=0.000e+00
runtime: p=1.282e-245
popularity: p=0.000e+00
vote_average: p=0.000e+00
vote_count: p=0.000e+00
revenue: p=0.000e+00

## Task 4 — Save Cleaned Data 

I saved the cleaned dataset as data/newdata.csv. 
This file will be used for the rest of the project.

In [24]:
import os

# save cleaned dataframe
os.makedirs("data", exist_ok=True)
df.to_csv("data/newdata.csv", index=False, encoding="utf-8")

print("saved cleaned dataset to data/newdata.csv")

saved cleaned dataset to data/newdata.csv